### PR TITLE
Fix aggregateRating schema on product page

### PR DESCRIPTION
**Pull request by rodriciru**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add aggregaterating to schema.org markup
| Type?             | improvement

### CODE REVIEW

**Comment by rodriciru** [comment]
Also, i can't find any implementation of the first if, so maybe it can be deleted
`{if isset($nbComments) && $nbComments && $ratings.avg}"aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "{$ratings.avg|round:1|escape:'html':'UTF-8'}",
      "reviewCount": "{$nbComments|escape:'html':'UTF-8'}"
    }`

**Comment by NeOMakinG** [comment]
@rodriciru Please, could you make some efforts on filling the PR description? Sometimes we're pretty free not serving it for some apparent things or whatever, but we need some input here

**Comment by rodriciru** [comment]
Sorry!
I think it will be self-explanatory

**Comment by rodriciru** [comment]
Im working on add review to schema, but I have some problems

**Comment by NeOMakinG** [comment]
@rodriciru I guess we can at least merge this one? And add reviews inside another PR?

**Pull request merged**
