### PR TITLE
productcomments - Make rating mandatory

### PR DESCRIPTION
**Pull request by leemyongpakvn**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Implementation of productcomments' MakeReviewMadatory for hummingbird
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #PrestaShop/PrestaShop/issues/26001
| Sponsor company   | Your company or customer's name goes here (if applicable).
| How to test?      | Apply PR change then check to make sure Review with **Empty** title, author, description or **NotChosen** rating won't be accepted. <br/> (Don't forget to clone a clean develop branch of hummingbird, as well as clear browser cache, PS cache before testing ;)

### CODE REVIEW

**Review by mflasquin — APPROVED** [review]

**Review by paulnoelcholot — APPROVED** [review]

**Review by kpodemski — DISMISSED** [review]
Blocking not to merge before productcomments PR.

**Comment by leemyongpakvn** [comment]
@paulnoelcholot Please recheck https://github.com/PrestaShop/productcomments/pull/197

**Comment by AureRita** [comment]
Hi @kpodemski, 

The PR is now merged, 

@leemyongpakvn can you apply your last changes on this PR ? 

Thank you

**Comment by leemyongpakva** [comment]
@AureRita The last commit in https://github.com/PrestaShop/productcomments/pull/197 stays in module's JS. There is no change needed for theme.

**Review by SharakPL — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by leemyongpakva** [comment]
@kpodemski The productcomments PR is now merged.

**Comment by leemyongpakva** [comment]
@AureRita We are in need or re-QA

**Review by AureRita — APPROVED** [review]

**Pull request merged**
