### PR TITLE
Add demo link

### PR DESCRIPTION
**Pull request by MatShir**
@pawelkierklo is proving us a demo. Big thanks !

### CODE REVIEW

**Review by matks — CHANGES_REQUESTED** [review]
Hi @MatShir I am sorry I am against this change.

I explain: it's really nice from @pawelkierklo but if we put this link inside the README, then we also set very high expectations.

If you are a github user and you go on any GitHub project, you expect that if there is a demo link in the README it is up to date.

Does @pawelkierklo commit to update his demo _every time we merge something in the `dev` branch_? Does he commit to keep it running 24H/24H, 7 days on 7? Does he commit to troubleshoot it when it has bugs?

If he does it's really cool 😄 

If he can't (and it's totally acceptable because it's very high expectations) then we should not put this link in the README. It's better to have NO demo instead of an OUTDATED demo.

Yes :/ demos are expensive and time-consuming to maintain

**Comment by MatShir** [comment]
We can share the release version and a comment to report if there is an issue. Let's be simple and not overthink.

**Comment by MatShir** [comment]
If the demo is down, it's not the end of the world. We remove the link when it is reported.

**Comment by pawelkierklo** [comment]
I will update, I can also prepare a cron.php that will do it for me. I want to develop HB. Let's go!

**Comment by MatShir** [comment]
Hi @pawelkierklo, 
As a new member of the community, we are 100% confident to have a demo which we don't have full control of. But we appreciate your involvement in the project, keep going 💪

**Comment by pawelkierklo** [comment]
Ready! CRON will update "develop" theme on demo every night

**Comment by MatShir** [comment]
Hi @pawelkierklo, 
Sorry for the back and forth, could you share the demo in the [discussion on Showcase category](https://github.com/PrestaShop/PrestaShop/discussions/new?category=showcase). Then, we will link the issue here, so later on if users can share report and feedback on the thread directly ;)

**Pull request closed without merging**
