### PR TITLE
Fix some scss vars and tpls

### PR DESCRIPTION
**Pull request by rodriciru**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | IF we customize card-bg color, quick view It's still white, so it looks like a Picasso. Also, i add some changes and new classes to other elements
| Type?             | bug fix
| BC breaks?        |  no
| Deprecations?     |  no

By default, $card-bg it's white, so there are no visible changes.

Problem:
imagen

Solution (if we choose this wonderful red 😀):
imagen

Account identity old (same as old address):
imagen

Account identity new (bg and padding) (same as new address)
imagen

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@rodriciru 

https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=236%3A10538

We should follow the mockups as much as possible, except if we have a really needed choice to do.

I guess the background on `My Account` pages is just a design choice which we shouldn't take the liberty to decide ourself while some designers worked on it

**Comment by rodriciru** [comment]
Well, I'm not so sure, but I can't guarantee it.

First, I use this light gray (SCSS lighten($gray-100, 2%)) because I see on other forms, but maybe it should be white as Figma. My bad.

Supposing I choose white instead of this gray:
As the bg in the page is white, you can have a bg on the form, and because it's white you won't notice it. In other parts of the customer account, you have this white bg, so I deduced it's a CSS mistake o whatever. But as I say, I can't guarantee it.

And please, keep in mind that this imgs that I posted on this PR, **has my own bg color** for the body (gray), so when stock theme you won't notice the bg, just when you decide to change the bg

I do this, to maintain a consistence between pages on the customer account, when change the bg to other than white

**Comment by Hlavtox** [comment]
@rodriciru I think I get your idea, but changing the background usually requires to add some paddings around content with white background. So it will never be just 'change one var and done'...

**Comment by rodriciru** [comment]
> @rodriciru I think I get your idea, but changing the background usually requires to add some paddings around content with white background. So it will never be just 'change one var and done'...

That's right. And in this case it is. This was one of my problems, and I add some padding ( I copy from other form), because I think the drawbacks are less than the benefit in pro of customization.

You are the bosses on this theme, so whatever yours decide will be the best.

**Comment by NeOMakinG** [comment]
It didn't move for a while, as we switched to default bootstrap colors and CSS vars, it's probably over already

if @rodriciru want's to change something again, feel free to pick it up, reopen it or open a new PR

**Pull request closed without merging**
