### PR TITLE
Improve blockcart modal

### PR DESCRIPTION
**Pull request by mparvazi**
https://user-images.githubusercontent.com/85633460/172021708-80f66680-ffeb-4748-afd9-cf046e772021.mp4

### CODE REVIEW

**Comment by mparvazi** [comment]
@NeOMakinG 

There is some rules for modal header in [productcomments](https://github.com/PrestaShop/productcomments) that will impact modal header display globally:

https://github.com/PrestaShop/productcomments/blob/e533da1e68a43f5a7fea0dc8d225d5baccc275cb/views/css/productcomments.css#L198

**Review by matks — COMMENTED** [review]
Looks good for me 👍

**Comment by Hlavtox** [comment]
> There is some rules for modal header in [productcomments](https://github.com/PrestaShop/productcomments) that will impact all modal headers display in product page:

oh god 🤦‍♂️😂

**Comment by NeOMakinG** [comment]
> https://github.com/PrestaShop/productcomments/blob/e533da1e68a43f5a7fea0dc8d225d5baccc275cb/views/css/productcomments.css#L198

We definitely need to change this 😆

**Review by NeOMakinG — APPROVED** [review]

**Pull request merged**
