### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 0.2.0
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @matthieu-rolland ,

Tested all the PRs of this release.

I have found a few things that need to be checked ^^

- Related to https://github.com/PrestaShop/hummingbird/pull/541
In Shopping cart page, when you put 0 on the quantity and press Enter, the product won't be removed :x:
The product is removed only when you click on the Checkmark.

https://github.com/PrestaShop/hummingbird/assets/16019289/19d3732f-d39b-421c-a267-727ad491b159

- Related to https://github.com/PrestaShop/hummingbird/pull/548
When you add a product with a minimal quantity to your cart, the product quantity should be updated. 
Example : my minimal quantity is 3, I add 3 products to my cart, I Continue shopping, I should be able to add just 1 product to my cart instead of 3. :x:
The behavior in the shopping cart is correct ✅ 

https://github.com/PrestaShop/hummingbird/assets/16019289/5d079315-3976-4022-ab30-7a1abb2ffb01

- Related to https://github.com/PrestaShop/hummingbird/issues/546
Tested with this file :
Screenshot 2024-02-23 at 14 59 44

Here's the result :x:

https://github.com/PrestaShop/hummingbird/assets/16019289/c8d1d6ad-7f02-4b0f-9c68-51f09b7b150c

- Related to https://github.com/PrestaShop/hummingbird/pull/568
For the module productcomments, the stars are not displayed on category page :x:

https://github.com/PrestaShop/hummingbird/assets/16019289/a0d79724-38e1-486a-8384-64c585d6a15e


Thanks 🚀

**Comment by AureRita** [comment]
Hi @boherm 

Thank you for your PR, currently I tested it and, yes, the logo is a little bit smaller but I think it's not enought as you can see : 

image


FYI : you can scroll under the logo 

Can you correct it ? 

Waiting for your feedback

**Comment by nicosomb** [comment]
About the QA done by @florine2623, I opened new issues: 
#622 
#623 
#624 
#625 

We can go forward with this PR to release 0.1.7.

**Comment by amine-O** [comment]
Ok for release, bugs can be solved and merged later

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
