### PR TITLE
New webpack config 

### LINKED ISSUE #31: [Dev Tools] Refacto Webpack configuration
We need to refacto the webpack configuration in order to be able to use webpack dev server for a better development experience.

### PR DESCRIPTION
**Pull request by Oksydan**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | New webpack config. More desc soon I will try to document it. It ain't finished yet. Commands `npm run build`, `npm run watch`/`npm run dev` are working but I am not done with it yet. 
| Type?             |  improvement 
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #31.
| How to test?      | It should compile files. I think @NeOMakinG should be able to test it and approve. No QA needed here. 
| Possible impacts? | Everything should be working as before but with more features. 

I am going to test it and fix some issues. 
Known issues:
- [x] CleanWebpackPlugin isn't working - replaced with https://webpack.js.org/configuration/output/#outputclean
- [x] remove swiper script,
- [x] bundleAnalizer will receive its own npm script with build to don't break CI/CD that may relay on that build script,
- [x] have to test esbuild-loader with ts files,
- [x] add ForkTsCheckerWebpackPlugin to check TS types.
- [x] publicPath requires discussion 

@NeOMakinG It is working and compiling you are able to test it atm and provide some feedback. 

To make it working copy `.env-example` and create `.env` in the same directory. Fill values depending on your local prestashop installation.

### CODE REVIEW

**Comment by Oksydan** [comment]
@Hlavtox yes, since publicPath is defined inside env file it will be undefined. 
Should we inform inside CLI about not existing .env file and exit form executing script?

**Comment by NeOMakinG** [comment]
I didn't test this yet, I need to do it today in order to confirm that this works with a vhost and without, that's it :p

**Comment by Hlavtox** [comment]
@kpodemski So everyone who wants to use this theme needs to configure his build environment and build it? WTF :D

How do you want to distribute it?

**Comment by Oksydan** [comment]
@NeOMakinG it is't going to work w/o vhost. 
We can stay to relative path but we will not be able to use dynamic import.
Existence of forked version for devs makes sens now 😄

**Pull request merged**
