### PR TITLE
Add quickview touch button for mobile

### LINKED ISSUE #291: Different display for quickview on touch screen
In screens that hover not works, need to show quickview button in product box.
```scss
// hide quickview touch button

@media (hover: none) and (pointer: coarse) {
  // hide hover quickview box
  // show quickview touch button
}
```

https://user-images.githubusercontent.com/85633460/169580931-bf914e64-b7d7-4445-a358-47909cde0766.mp4

### PR DESCRIPTION
**Pull request by mparvazi**
Fixes #291

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]
Nice work, just a comment to think about - what would you say about making the button styling universal, like `product-miniature__action-button` - so we can have the same styling for wishlist and others?

**Comment by mparvazi** [comment]
> Nice work, just a comment to think about - what would you say about making the button styling universal, like `product-miniature__action-button` - so we can have the same styling for wishlist and others?

Currently we don't have any access to wishlist button template in theme.

@NeOMakinG wdyt?

**Comment by Hlavtox** [comment]
@NeOMakinG We should return that hook dude... it was removed for performance reasons, but isn't calling a php function 24 times still faster than loading a javascript for that?

**Comment by NeOMakinG** [comment]
> @NeOMakinG We should return that hook dude... it was removed for performance reasons, but isn't calling a php function 24 times still faster than loading a javascript for that?

I guess no, overwise we would have kept it

Calling a dumb function doesn't cost so much, but calling `numberOfProduct * numberOfModulesUsingTheHook * some SQL request` and more can be really dangerous

But there is another way to be able to override that button for our styling guys, we should add some changes this to `blockwishlist`

**Review by NeOMakinG — APPROVED** [review]
Nice thing 👍

**Pull request merged**
