### PR TITLE
Fixed bootstrap slider display bug on product page

### LINKED ISSUE #504: Product image slider make a bug when sliding rendering image bigger during transition.
Product image slider make a bug when sliding by rendering image bigger during few milliseconds. This is due to the size of the image that is smaller to his container and make, and the slider make it 100% width during the image translate, so this creates a little shift. (More visible with screens < 992px & > 767px)

### PR DESCRIPTION
**Pull request by GytisZum**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fixed display issue when changing image on carousel in product page on a smaller screen with different size of images. The issue was caused by bootstrap classes which was inserting display block instead of flex for a very short time which causes image to resize.
| Type?             | bug fix
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes #504 
| Sponsor company   | PrestaShopCorp
| How to test?      | Test slider on product page with different size images and different size screens. Slider must be stable and do not change the size. No content should be shifting.  Best visibility is on 800-1000px screen width.

Bootstrap automatically adds transition classes and one of the transition classes is `display block` while other classes are `display flex`. For a short time you can see image resize due to display differences
Previously:
As you can see image is to big for its size and these classes has 
```
.carousel-item.active, .carousel-item-next, .carousel-item-prev {
  display: block;
}
```
image

After:
image

### CODE REVIEW

**Comment by kpodemski** [comment]
scss linter 🔴

**Review by M0rgan01 — APPROVED** [review]

**Review by ga-devfront — DISMISSED** [review]
small fix and work well thank you

**Review by kpodemski — APPROVED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Review by sallemiines — COMMENTED** [review]
Hello @GytisZum 
Thanx for the PR 

- PR testesd with PS810
- [Tests autos](https://github.com/sallemiines/ga.tests.ui.pr/actions/runs/5312094229) OK µ
- Before installing the PR I have this behavior : 

https://github.com/PrestaShop/hummingbird/assets/31663369/76d7682b-448b-4cfe-81a1-6bb1bd4e789b



- After installing the PR  I noticied that : 
in the first image loading there is a little visual problem when loading images in the first click images are displayed in small icons,once all displayed(by clicking next slider),the display become normal

 you can check this video bellow 


https://github.com/PrestaShop/hummingbird/assets/31663369/51b6cb16-5d79-4ff0-b3ae-e4b0f5bb5861


Could you please check  is that the expected behavior  ? 
Waiting for you ! 
Thank you

**Comment by GytisZum** [comment]
> 

Hello, 

After doing several tests found that on `develop` branch this issue still exist. To recreate it  and make it visible its enough to add throtle with developer tool on network tab by making a poor connection (3G good/bad), however I was able to to get poor CLS with good internet connection . Thats definelty an issue as after doing some tests with google lighthouse found that this shifting causes bad score on page load and needed to be fixed.
CLS score 
image

The slider shift all the content below:
For example:
image
image
image

**Comment by GytisZum** [comment]
Fixed layout shifting which could be seen with google lighthouse tool and with the poor connection. Slider on load was pushing other elements below. Now on page load slider image has his own place where he will be once its rendered

Before:
image

After:
image

**Review by kpodemski — CHANGES_REQUESTED** [review]
Could you please rebase your PR so it doesn't have merge commits? For such a simple change, I think you can squash everything into one commit.

**Comment by kpodemski** [comment]
Closing as it was fixed in another PR :)

**Pull request closed without merging**
