### PR TITLE
Fix: [FO]Carrier extra content not work on deliveryFormSelector change

### LINKED ISSUE #478: Carrier extra content not work on deliveryFormSelector change
Missing prestashop.on('updatedDeliveryForm', (params) => { ... });

### PR DESCRIPTION
**Pull request by GytisZum**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Previously delivery extra content was shown only on page load. Added Prestashop event for extra content to be dynamic, tried to recreate the slide down animation as close as in classic theme with content max-heigh property.
| Type?             | bug fix
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/hummingbird/issues/478
| How to test?      | Add product to cart. Sign in and complete step 1 and step 2 on checkout. On delivery option step select different deliveries. Make sure delivery option has module with has an hook `displayCarrierExtraContent` which add's extra content.

On page load:
image

Selecting method without extra content:
image

Selecting another method which has extra content:
image

### CODE REVIEW

**Review by ga-devfront — APPROVED** [review]
really good work, thank you !

**Review by Hlavtox — APPROVED** [review]

**Review by hibatallahAouadni — CHANGES_REQUESTED** [review]
Hello @GytisZum 

Thanks for your PR :pray: 
Unfortunately, it seems that the issue still not fixed with your PR, see the attached screen record below:

[hb-pr_496.webm](https://github.com/PrestaShop/hummingbird/assets/23308427/3d87664e-b86d-4d23-b00d-25c9c1f5bd1f)

Please check and feedback.

Thanks!

**Comment by GytisZum** [comment]
### Hello, 
Thank you for response and the video you provided, however I am unable to recreate same issue on different PrestaShop versions (8.1.0 | 8.0.2).
Could you please confirm that assets was builded as this PR have style file which has to be compiled. From video you provided it looks like they are missing that stylesheet.
If it is not the case could you please provide me your environment you test with.

- PrestaShop version.
- Browser.
- Operating system.
- Module you test with.

Please check and feedback
Thank you!

**Review by hibatallahAouadni — COMMENTED** [review]
Hello @GytisZum 

On `develop` branch :x: , I still encounter the same issue as you can see the first part of the attached screen record:

- PrestaShop version: `develop`
- Browser: Chrome 107.0.5304.87
- Operating system: Ubuntu 22.04.1 LTS
- Module you test with: `tox_extracarrier`

While with `8.1.x` branch :heavy_check_mark: , the issue is fixed as you can see the second part of the attached screen record:

- PrestaShop version: `8.1.x`
- Browser: Chrome 107.0.5304.87
- Operating system: Ubuntu 22.04.1 LTS
- Module you test with: `tox_extracarrier`

[pr_496.webm](https://github.com/PrestaShop/hummingbird/assets/23308427/7d3df74d-b71d-417d-9936-3edee31a1aa5)

Please check and feedback.

Thanks!

**Comment by hibatallahAouadni** [comment]
Please find attached the module I used to test this PR (developed by @Hlavtox )

[tox_extracarrier.zip](https://github.com/PrestaShop/hummingbird/files/11496836/tox_extracarrier.zip)

**Comment by guizme555** [comment]
Hello @hibatallahAouadni ,
I just tested on the develop branch and it works well (and I did clear my browser cache).
My configuration :
- PrestaShop version: `develop`
- Browser: Chrome Version 113.0.5672.92 (Build officiel) (arm64)
- Operating system: Mac OS  Ventura 13.3.1 (a) (22E772610a)
- Module you test with: `tox_extracarrier`

**Review by sallemiines — APPROVED** [review]
Hello @GytisZum 

Thanx for the PR ! 
Pr checked with `develop` , `PS804` & `PS810-rc` => OK 

https://github.com/PrestaShop/hummingbird/assets/31663369/403ccc7d-02fc-40dd-b155-0d1d61e41d51

LGTM ! QA :heavy_check_mark:

**Review by hibatallahAouadni — APPROVED** [review]
Hello @GytisZum 

LGTM too, it seems to be a cache issue on my side :sweat: 

[pr_496.webm](https://github.com/PrestaShop/hummingbird/assets/23308427/74daaf40-c791-4ae6-8e4e-2050f29c1a99)

As you can see it works on develop branch too.

Thanks!

**Comment by nicosomb** [comment]
thank you @GytisZum !

**Pull request merged**
