### PR TITLE
Revert token replacement

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Reverts dirty token fix, it broke address forms.
| Type?             | bug fix
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | -
| Sponsor company   | -
| How to test?      | -

### CODE REVIEW

**Comment by nicosomb** [comment]
@Hlavtox why all your jobs are red?

**Comment by Hlavtox** [comment]
@nicosomb `The job was not started because recent account payments have failed or your spending limit needs to be increased. Please check the 'Billing & plans' section in your settings.`

**Comment by nicosomb** [comment]
@Hlavtox OK, I see. I will try contact the good person.

**Comment by Hlavtox** [comment]
Ping @nicosomb All good

**Review by nicosomb — APPROVED** [review]

**Comment by NeOMakinG** [comment]
@Hlavtox this revert will cause some issues with the cache on product lists

**Comment by Hlavtox** [comment]
Yes but it broke address forms completely, we need to find a better way to do it 👍

**Pull request merged**
