### PR TITLE
order return table fix

### PR DESCRIPTION
**Pull request by JBLach**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | I have fixed return table on return details page
| Type?             | improvement
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Fixes NA.
| How to test?      | See screenshots below.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

## Before
image
image

## After
image
image

## Screenshot update
image
image
image

### CODE REVIEW

**Comment by SharakPL** [comment]
What does it fix exactly? TBH I like when attributes are always visible. I would maybe change the placement (a list under the title would be better).

**Comment by JBLach** [comment]
> What does it fix exactly? TBH I like when attributes are always visible. I would maybe change the placement (a list under the title would be better).

i improved the look of the table like we have on other user pages, i can see that i forgot to add the reference code on mobile view, I made a screenshot of the products without attributes, so you can't see them , if exist should be visible next to the product name as before

**Comment by JBLach** [comment]
@kpodemski yes i will add what i forgot and change the position of the table as suggested by SharakPL, I'll take care of it now

**Review by NeOMakinG — APPROVED** [review]
🍬

**Review by kpodemski — APPROVED** [review]

**Pull request merged**
