### PR TITLE
Templates: double quotes => single quote (for Smarty strings)

### PR DESCRIPTION
**Pull request by yannicka**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Chunk of #593. Strings in Smarty templates all (or almost all) use single quotes instead of double quotes.
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | N/A
| Sponsor company   | N/A
| How to test?      | Install the theme and browse the website.

### CODE REVIEW

**Review by kpodemski — DISMISSED** [review]

**Review by Hlavtox — DISMISSED** [review]

**Comment by kpodemski** [comment]
@yannicka after the merge of one of your PRs there are some conflicts there :( probably it will be a bit of a pain since your previous PR changed spaces 😓

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @yannicka ,

I tested with develop branch of PS and PHP 8.1.

I have an internal server error when installing the hummingbird theme PR.

Screenshot 2024-02-28 at 09 40 54

With classic theme, it works as expected.

Could you check ? :)
Thanks!

**Comment by kpodemski** [comment]
@florine2623, could you check what the logs say? because this is just a generic error message

**Comment by yannicka** [comment]
For my part, I can install the theme with this modification, and the theme works.

If you activate debug mode, it will display more information.

**Review by florine2623 — APPROVED** [review]
Hello @yannicka ,

Retested the theme on `develop`. I do not have any errors. Probably a problem with my server 😅 

Tested :
- creation of a product in BO and checked product page in FO
- checked categories page
- log into customer page
- checked customer account pages 
- processed to checkout
- checked content pages

LGTM ✅

**Pull request merged**
