### PR TITLE
Add row class fallback to productlist.tpl and remove every css override

### PR DESCRIPTION
**Pull request by rodriciru**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | .row class is missing so BS wont work
| Type?             | bug fix
| BC breaks?        |  no
| Deprecations?     | no

Before:
imagen
After:
imagen

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Comment by Hlavtox** [comment]
We should make some kind of a fallback for modules not passing this parameter I think. 🤔

**Comment by NeOMakinG** [comment]
@Hlavtox feel free to merge when you feel like :)

**Review by jolelievre — APPROVED** [review]
Thanks @rodriciru

**Comment by jolelievre** [comment]
@Hlavtox @NeOMakinG 

I don't really know the process for validating/merging PRs on this repo, is there some QA done at some point? If yes by who?

**Comment by mparvazi** [comment]
Hello @rodriciru 

For modules, the templates inside `<section>` it's better to be wrapped by `<div class="container"> `

Currently missed on:
ps_categoryproducts.tpl
ps_crossselling.tpl
ps_viewedproduct.tpl


Screenshot from 2022-07-11 15-10-40

**Review by mparvazi — CHANGES_REQUESTED** [review]
Hello @rodriciru 

For modules, the templates inside `<section>` must be wrapped by `<div class="container"> `

Currently missed on:
ps_categoryproducts.tpl
ps_crossselling.tpl
ps_viewedproduct.tpl

**Comment by NeOMakinG** [comment]
> For modules, the templates inside `<section>` block must be wrapped by `<div class="container"> `
> 
> Currently missed on:
> 
> * ps_categoryproducts.tpl
> * ps_crossselling.tpl
> * ps_viewedproduct.tpl

I'll continue taking over this PR, will add this later in the day, thanks for testing @mparvazi

**Comment by NeOMakinG** [comment]
> @Hlavtox @NeOMakinG
> 
> I don't really know the process for validating/merging PRs on this repo, is there some QA done at some point? If yes by who?

There is no QA process for the moment, it will probably be set up after the first beta release, most of the time, contributors and myself are still testing the PR before merging

And I really love that honestly, I'll try to keep a similar workflow in the future as a test, if the QA agree, would be awesome as it's really flexible and seems like it's not a pain for the moment

**Comment by Hlavtox** [comment]
@jolelievre Yeah, for now, the development phase, we just check each others work and merge it. It would develop 10x slower if we had to wait for QA every time.

**Review by mparvazi — APPROVED** [review]

**Comment by mparvazi** [comment]
@jolelievre 

No problem, I try to test everything before merge.

**Comment by Hlavtox** [comment]
@mparvazi @NeOMakinG @SharakPL @rodriciru I am still thinking, can we do it somehow, that we define the columns only in productlist.tpl? 🤔 Is it possible to detect the layout in that file and have 3 configs to automatically use? So the tpls that include it don't have to think about it.

So it can look only like: `{include file="catalog/_partials/productlist.tpl" products=$products}`

**Comment by NeOMakinG** [comment]
> @Hlavtox does it mean there is at least a developer who gets the branch and tests it a bit? or it's only review, approve and merge?

Most of the time we are testing PRs ourself, it doesn't mean that we merge blindly

**Comment by NeOMakinG** [comment]
> @mparvazi @NeOMakinG @SharakPL @rodriciru I am still thinking, can we do it somehow, that we define the columns only in productlist.tpl? 🤔 Is it possible to detect the layout in that file and have 3 configs to automatically use? So the tpls that include it don't have to think about it.
> 
> So it can look only like: `{include file="catalog/_partials/productlist.tpl" products=$products}`
> 
> I know we implemented this in classic together, but MAYBE there is a better solution.

There is 2 different layout, listing from homepage and listing inside a container, I guess this is why we implemented this

Maybe there is a better solution as @SharakPL we could use some layouts with grids

Btw, as this is another refactor discussion, I would suggest merging this PR, and create an issue about improving that system, or we take the risk to get stuck between 2 buggy states if no one takes the refactoring subject :)

**Comment by SharakPL** [comment]
@NeOMakinG I'm on it! 🙋

**Pull request merged**
