### PR TITLE
Add useAlert

### PR DESCRIPTION
**Pull request by mparvazi**

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Hey @mparvazi would you mind writing the documentation as I did for `useToast` or do you want me to do it?

**Comment by mparvazi** [comment]
> Hey @mparvazi would you mind writing the documentation as I did for `useToast` or do you want me to do it?

If there is no hurry, then I'd like to write doc for first time in my life :)

**Comment by NeOMakinG** [comment]
> > Hey @mparvazi would you mind writing the documentation as I did for `useToast` or do you want me to do it?
> 
> If there is no hurry, then I'd like to write doc for first time in my life :)

Don't hesitate to use the `useToast` doc as a base

**Comment by mparvazi** [comment]
Can this PR be merged first?

**Review by NeOMakinG — APPROVED** [review]

**Comment by NeOMakinG** [comment]
Thanks @mparvazi ❤️

**Pull request merged**
