### PR TITLE
Fix category duplication and image sizes

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | When filtering, top categories are duplicated, and images sizes were wrong
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no

### CODE REVIEW

**Comment by lramos-prolaser** [comment]
Hello!
I had an undefined index home_default error because you forgot to add `bySize` in `data-full-size-image-url`, `width` and `height` attributes. To fix it:
```
            {if $product.cover}
              <img
                src="{$product.cover.bySize.home_default.url}"
                alt="{if !empty($product.cover.legend)}{$product.cover.legend}{else}{$product.name}{/if}"
                loading="lazy"
                data-full-size-image-url="{$product.cover.bySize.home_default.url}"
                width="{$product.cover.bySize.home_default.width}"
                height="{$product.cover.bySize.home_default.height}"
                class="{$componentName}__image card-img-top"
              />
```

**Comment by Hlavtox** [comment]
@lramos-prolaser Fixed dude, I'm blind, update your code pls ;-)

**Comment by lramos-prolaser** [comment]
Thanks! :-)

**Comment by NeOMakinG** [comment]
> Hello! I had an undefined index home_default error because you forgot to add `bySize` in `data-full-size-image-url`, `width` and `height` attributes. To fix it in `/_partials/miniatures/product.tpl`:
> 
> ```
>             {if $product.cover}
>                                src="{$product.cover.bySize.home_default.url}"
>                 alt="{if !empty($product.cover.legend)}{$product.cover.legend}{else}{$product.name}{/if}"
>                 loading="lazy"
>                 data-full-size-image-url="{$product.cover.bySize.home_default.url}"
>                 width="{$product.cover.bySize.home_default.width}"
>                 height="{$product.cover.bySize.home_default.height}"
>                 class="{$componentName}__image card-img-top"
>               />
> ```

Yeah my bad, sorry :)

**Pull request merged**
