### PR TITLE
Add useQuantityInput

### PR DESCRIPTION
**Pull request by mparvazi**
https://user-images.githubusercontent.com/85633460/159935005-1b8adacd-97ca-404d-9dfb-ca09a760a59a.mp4

### CODE REVIEW

**Comment by SharakPL** [comment]
Total on the product line in the cart needs to update as well on quantity change. It doesn't on the video.

**Comment by mparvazi** [comment]
> Total on the product line in the cart needs to update as well on quantity change. It doesn't on the video.

Something is wrong in tpl file for product line.
Will be fixed by @NeOMakinG

**Comment by NeOMakinG** [comment]
@mparvazi fixed now

**Comment by mparvazi** [comment]
@NeOMakinG 

It's ready to merge.

**Comment by matthieu-rolland** [comment]
could we have a proper description for this PR ?

**Review by matthieu-rolland — COMMENTED** [review]
could we have a proper description for this PR ?

**Review by NeOMakinG — APPROVED** [review]

**Pull request merged**
