### PR TITLE
No Carousel on no image product

### PR DESCRIPTION
**Pull request by rodriciru**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Update on Merged PR 283
| Type?             | improvement 
| BC breaks?        | no
| Deprecations?     |  no

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
From a code perspective logic, it looks fine, but didn't tested it yet

**Comment by rodriciru** [comment]
> From code logic, it looks fine, but I didn't test it yet

imagen
blued part is .product__left.col-lg-6.col-xl-7 so as you can see, image fits perfect in his space. Also in mobile

**Comment by NeOMakinG** [comment]
Just tested it, looks fine :)

**Review by Hlavtox — APPROVED** [review]
All good for me!

**Pull request merged**
