### PR TITLE
Overwriting productListingComments.js with the correct product selector

### PR DESCRIPTION
**Pull request by chrisai-dev**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Product reviews/comments weren't loaded via ajax on the category page.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | ~~View a category that has products with reviews~~ Check if theme correctly hook productcomments module

To test it, go to a shop where the Classic theme and Hummingbird theme are installed.

1. Make the Classic theme active and ensure the Product Comments module is active if it's not already.
2. Unhook the Product Comments module from the following hooks (BO: **Design -> Positions**):
   - `displayFooterProduct`
   - `displayProductAdditionalInfo`
   - `displayProductListReviews`
3. Change the theme to Hummingbird.
4. Check in **Design -> Positions** if the Product Comments module is correctly hooked into the above hooks.

### CODE REVIEW

**Comment by SharakPL** [comment]
This should be fixed already. Try fresh hummingbird and productcomments module min v.6.0.3

**Comment by chrisai-dev** [comment]
The query selector was fixed in https://github.com/PrestaShop/productcomments/pull/198/commits/51a0320c41e82a1ba08b6ee2a648a1a670019f74

but the PR is still needed for the theme.yml config.

**Review by tblivet — APPROVED** [review]
Hi @chrisai-dev, I agree with you, theme.yml need an update to properly hook the module 👍 even if the PR name does not address the right issue !

**Review by florine2623 — COMMENTED** [review]
Hello @chrisai-dev ,

Thanks for the PR !

I followed the steps, they seem to work. But when I switch back to Classic theme, the hooks are hooked again.

1. Make the Classic theme active and ensure the Product Comments module is active if it's not already.
2. Unhook the Product Comments module from the following hooks (BO: Design -> Positions):
`displayFooterProduct`
`displayProductAdditionalInfo`
`displayProductListReviews`
3. Change the theme to Hummingbird.
4. Check in Design -> Positions if the Product Comments module is correctly hooked into the above hooks. ✅ 
5. Go to Design > Theme & Logo > Use this theme for Classic
6. Check in Design -> Positions, Product Comments module is hooked to the following `displayFooterProduct` 
`displayProductAdditionalInfo` 
`displayProductListReviews`
It should not :x:

Could you check ?
Thanks!

**Comment by tblivet** [comment]
Hi @florine2623,

You mean, when you switch from Hummingbird to Classic, the module productcomments hooks again on `displayFooterProduct`, `displayProductAdditionalInfo`, and `displayProductListReviews`. If that's the case, it's normal because both themes need to correctly hook the module to these hooks.

What @chrisai-dev has done is reproduce the behavior of Classic, which was correct but missing in Hummingbird. I don't know if this is clear ? Don't hesitate to let me know if it's not.

**Comment by florine2623** [comment]
Hello @tblivet ,

Ok, it is clear to me. Thanks for the details ^^

**Comment by jolelievre** [comment]
Thanks @florine2623 and @chrisai-dev

**Pull request merged**
