### PR TITLE
Improve readme title

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Improve readme
| Type?             | improvement

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]

**Comment by kpodemski** [comment]
@matks, shouldn't the repo name be `hummingbird-theme`?

**Comment by NeOMakinG** [comment]
> @matks, shouldn't the repo name be `hummingbird-theme`?

If we do this, we are forced to `git clone <urlrpo> hummingbird` because of the config.yml, and add the word `theme` to a subfolder of `themes` looks wrong

**Comment by NeOMakinG** [comment]
@kpodemski if you want to talk about it, open an issue or slack!

**Comment by kpodemski** [comment]
@NeOMakinG 

it's exactly the same with the `classic`, this is why I thought we want to follow this naming convention 👍 

not that important tbh

**Comment by NeOMakinG** [comment]
> @NeOMakinG
> 
> it's exactly the same with the `classic`, this is why I thought we want to follow this naming convention 👍
> 
> not that important tbh

Yeah and this is exactly why I said to @matks that classic repository shouldn't be named like this :(

**Comment by NeOMakinG** [comment]
> Maybe we need to rename `classic-theme` to `classic` then 🤔

@eternoendless wdyt? Do we have some constraint about this?

**Comment by eternoendless** [comment]
I named classic-theme that way because "classic" is a generic word and I thought it could be confusing otherwise. I'm not sure if we can rename the source of a composer package in packagist. Perhaps we can.

The package is still named `prestashop/classic` because the package name determines the installation directory and that unfortunately cannot be changed. Plus, the translation system does not support dashes in the module/theme name either.

The git clone issue is just a small inconvenience in my opinion, anyway the normal way to include a theme should be through composer (unless you're planning on working on the theme itself).

**Pull request merged**
