### PR TITLE
Update bootstrap and use css variables

### LINKED ISSUE #186: Color variables needs to be reviewed
**Current color overrides:**

`src/scss/partials/variables/bootstrap/_variable-overrides.scss`
| Sass | Color | Contrast Ratio* | WCAG AA | BS5 !default |
| :---         |     :---:      |    :---:      | :---         |    :---:      |
| $primary   | `#5434d0`   | 7.55:1   | Pass   | `#0d6efd`   |
| $secondary   | `#f39d72`   | 9.87:1   | Pass   | `#6c757d`   |
| $Info**   | `#f39d72`   | 9.87:1   | Pass   | `#0dcaf0`   |
| $success   | `#4cbb6c`   | 2.43:1   | Fail   | `#198754`   |
| $warning   | `#ff9a52`   | 9.99:1   | Pass   | `#ffc107`   |
| $danger   | `#ff4c4c`   | 3.28:1   | Fail   | `#dc3545`   |

`src/scss/partials/variables/prestashop/_colors.scss`
| Sass | Color | Contrast Ratio* | WCAG AA | BS5 !default |
| :---         |     :---:      |    :---:      | :---         |    :---:      |
| $default-icon-color   | `#6c868e`   | 3.86:1   | Fail   | -   |
| $footer-background-color   | `#011638`   | 17.9:1   | Pass   | -   |

\* _For [contrast checking](https://webaim.org/resources/contrastchecker/) I used colors as background and white or black as foreground color._
** _The **$info** color basically should be in blue color tone._

**These files have been used the hard coded colors:**
```
src/scss/error.scss
src/scss/core/components/_breadcrumb.scss
src/scss/core/modules/nouislider/_vars.scss
src/scss/custom/components/_order-confirmation.scss
src/scss/custom/components/customer/_customer-menu.scss
src/scss/custom/layout/_footer.scss
```

## BS5

**gray-color-variables**
| Sass | !default |
| :---         |     :---:      |
|$white:   |`#ffffff`|
|$gray-100 |`#f8f9fa`|
|$gray-200 |`#e9ecef`|
|$gray-300 |`#dee2e6`|
|$gray-400 |`#ced4da`|
|$gray-500 |`#adb5bd`|
|$gray-600 |`#6c757d`|
|$gray-700 |`#495057`|
|$gray-800 |`#343a40`|
|$gray-900 |`#212529`|
|$black:    |`#000000`|

**color-variables**
| Sass | !default |
| :---         |     :---:      |
|$blue    |`#0d6efd`|
|$indigo  |`#6610f2`|
|$purple  |`#6f42c1`|
|$pink    |`#d63384`|
|$red     |`#dc3545`|
|$orange  |`#fd7e14`|
|$yellow  |`#ffc107`|
|$green   |`#198754`|
|$teal    |`#20c997`|
|$cyan    |`#0dcaf0`|

### PR DESCRIPTION
**Pull request by NeOMakinG**
Use bootstrap CSS variables as much as we can

It will make it easier in the future to change any style on runtime

For the moment, bootstrap doesn't plan to use these global variables on component level so we can't provide a way to change the style on runtime properly

closes #186 #253

### CODE REVIEW

**Comment by NeOMakinG** [comment]
I won't merge this until it's stable

**Comment by mparvazi** [comment]
`templates/_partials/variables.tpl`

Why we should not use something like `_root.scss` for css vars?
Then we will have possibility to work with scss maps.

**Comment by NeOMakinG** [comment]
> `templates/_partials/variables.tpl`
> 
> Why we should not use something like `_root.scss` for css vars? Then we will have possibility to work with scss maps.

We wants a way to provide these colors from a backend somehow, this is why we need a `tpl`

**Comment by mparvazi** [comment]
@NeOMakinG 

can be `config.scss` as entry point like as `theme.scss` and `error.scss`?
then include in header tpl as `config.css` before `theme.css`?

**Comment by NeOMakinG** [comment]
> @NeOMakinG
> 
> can be `config.scss` as entry point like as `theme.scss` and `error.scss`? then include in header tpl as `config.css` before `theme.css`?

But how would we make these scss values dynamic, coming from a database?

**Comment by mparvazi** [comment]
Damn! CSS vars?
Dive to the dark theme :P

**Comment by atomiix** [comment]
@NeOMakinG a rebase will be needed here 😅

**Review by matthieu-rolland — COMMENTED** [review]
rebase needed ;) 

About the use of `var()`, is it changing the behavior or is it a good practice that we are now enforcing ?

**Comment by NeOMakinG** [comment]
> rebase needed ;)
> 
> About the use of `var()`, is it changing the behavior or is it a good practice that we are now enforcing ?

It's not a `good practice` and doesn't `change the behavior`, people customizing the theme will be able to change these colors without the need of a bundler or whatever by changing the variable value on CSS side

**Review by matthieu-rolland — APPROVED** [review]
lgtm

**Pull request merged**
