### PR TITLE
Fix: issue-494

### LINKED ISSUE #494: [UNFINISHED THINGS]  - Sytle product comment
Image

### PR DESCRIPTION
**Pull request by tblivet**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix https://github.com/PrestaShop/hummingbird/issues/494 : Several style improvements have been made on `productcomments`.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | 
| Fixed ticket?     | Fix https://github.com/PrestaShop/hummingbird/issues/494
| Sponsor company   | @PrestaShopCorp
| How to test?      | I think the entire `productcomments` module needs to be tested.

**Before:**
comments_before

**After:**
comments_after

### CODE REVIEW

**Review by nicosomb — DISMISSED** [review]

**Review by boherm — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @tblivet ,

Thanks for the PR ! 🎉 

Tested all elements in Configuration block.
Tested Reporting reviews
CRUD Review criterias
Pagination looks good
Rating star color is correct


## BUG 1

The button `Read user reviews` has an anchor a little to low. I can't see the name of the user who posted a comment.

https://github.com/PrestaShop/hummingbird/assets/16019289/45705915-d27e-46d6-88f2-0dfc630a229d

## BUG 2

Same issue with write your review button. It scrolls down but I don't see the button to write my review.
I actually expect it to open the modal so I can Write my review directly. What do you think ? I couldn't find any info on the issue regarding that topic.

https://github.com/PrestaShop/hummingbird/assets/16019289/880a25c1-13c9-4ea5-b7f9-060cf7465218

Thanks!

**Comment by tblivet** [comment]
Hi @florine2623,

Thank you for the QA !

**Bug 1:** I have noticed the bug you reported. However, I think this can be fixed outside this PR to address the problem globally if other links in the theme use scroll anchors.

**Bug 2:** You're right 👍 the "Write your review" button should open the modal directly, so I have made a new commit to correct it.

**Comment by ps-jarvis** [comment]
This pull request seems to contain new translation strings. I have summarized them below to ease up review:

- `Shop.Theme.Catalog`
    - [ ] `Products pagination`

(Note: this is an automated message, but answering it will reach a real human)

**Review by nicosomb — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @tblivet ,

BUG 2 is fixed ^^ ✅ 
Thanks!

**Pull request merged**
