### PR TITLE
Split JS/CSS bundles

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | We want to split our bundles to avoid loading unused code on different pages
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/hummingbird/issues/129.
| How to test?      | The theme should look as usual
| Possible impacts? | Style and JS

### CODE REVIEW

**Comment by SharakPL** [comment]
What about CCC? Won't it still make one big css and js file from all this?

**Comment by Hlavtox** [comment]
`###         path: assets/css/modules/shoppingcart.css`

This has no effect and we are where we started. The css file must be in the module folder overriding the original CSS, so it's loaded only when the module says so.

**Review by TheGera — APPROVED** [review]

**Comment by NeOMakinG** [comment]
> What about CCC? Won't it still make one big css and js file from all this?

I guess I tested it without CCC activated, or I missed something, but you should be right

**Comment by NeOMakinG** [comment]
> `### path: assets/css/modules/shoppingcart.css`
> 
> This has no effect and we are where we started. The css file must be in the module folder overriding the original CSS, so it's loaded only when the module says so.

Yeah but then tell me the solution, because some modules doesn't have any CSS stylesheets, what about them? 😢

**Pull request closed without merging**
