### PR TITLE
Fix a11y for header elements

### PR DESCRIPTION
**Pull request by mparvazi**
https://user-images.githubusercontent.com/85633460/166454389-b6eecc93-6e6c-4d33-a1f3-31b12e7b82cf.mp4

**Not fixed:**
Need to find a way for main menu items selection on keyboard.
When main menu item is on focus state, then the sub-menu must be displayed.

### CODE REVIEW

**Comment by NeOMakinG** [comment]
@mparvazi ping me on slack when you think that this one is ready :)

**Comment by mparvazi** [comment]
@NeOMakinG It's ready to merge.
Need to think more about main-menu on keyboard, and I'll make another PR for it.

**Comment by NeOMakinG** [comment]
> @NeOMakinG It's ready to merge.
> 
> Need to think more about main-menu on keyboard, and I'll make another PR for it. I think it can be fixed just with JS.

My guess is that we need to add an event listener on focus to the element

**Review by NeOMakinG — APPROVED** [review]
Looks fine, well done 👍

**Comment by mparvazi** [comment]
> > @NeOMakinG It's ready to merge.
> > Need to think more about main-menu on keyboard, and I'll make another PR for it. I think it can be fixed just with JS.
> 
> My guess is that we need to add an event listener on focus to the element

Yes, I tested but there is some little problems.
I wait until this PR #258 merged. then I play with `ps_mainmenu.ts`

**Comment by NeOMakinG** [comment]
> > > @NeOMakinG It's ready to merge.
> > > Need to think more about main-menu on keyboard, and I'll make another PR for it. I think it can be fixed just with JS.
> > 
> > 
> > My guess is that we need to add an event listener on focus to the element
> 
> Yes, I tested but there is some little problems. I wait until this PR #258 merged. then I play with `ps_mainmenu.ts`

You can always base a branch on it and rebase when it gets merged if needed

**Pull request merged**
