### PR TITLE
Reproducible installs with npm

### PR DESCRIPTION
**Pull request by tswfi**
Use `npm ci` to install packages. This obeys package-lock.json.

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Use `npm ci` to install packages. This is repeateable and obeys package-lock.json . See https://docs.npmjs.com/cli/v9/commands/npm-ci
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | its a readme :)

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Comment by tswfi** [comment]
eh, node 14.. hmm

**Comment by NeOMakinG** [comment]
> eh, node 14.. hmm

Pretty sure you can change it, the theme was running on node 18 a few months ago on my computer

**Comment by tswfi** [comment]
also rebased so that the new package-lock files are used

**Review by kpodemski — APPROVED** [review]

**Comment by tswfi** [comment]
Looking better

**Review by NeOMakinG — APPROVED** [review]

**Comment by kpodemski** [comment]
thanks @tswfi 💪🏻

**Pull request merged**
