### PR TITLE
Fix checkout with outstock product

### PR DESCRIPTION
**Pull request by ga-devfront**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | This fix is not the best fix we can do, but it works without touching any module or Core. We're disabling the checkout button on layout if any product is no more available, and we put the max limit of the product if you try to take more than in stock.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes [#485](https://github.com/PrestaShop/hummingbird/issues/485)
| Sponsor company   | @PrestaShopCorp
| How to test?      | Try to go to the cart page with limited product (without oops active) and put more than that is in stock.

### CODE REVIEW

**Review by guizme555 — APPROVED** [review]

**Comment by EmnaChou** [comment]
I m going to test this PR

**Review by EmnaChou — COMMENTED** [review]
Hello @ga-devfront 
1-There is no alert message when i add more items than available in stock 
2- i can add items as i want to the cart
Capture d’écran 2023-05-29 à 12 50 11
Capture d’écran 2023-05-29 à 12 49 58

**Review by EmnaChou — COMMENTED** [review]
Hello @ga-devfront 
I ve tested the issue again  after switching to the branch to ticket_485/fix_checkout_with_bad_quantity' ( i was before on pr-497) , the obtained results are the following ones : 
1- on Prestashop version 8.1.0 : **the quantity of product is not updated** but the pop up is n't on her good location ( on the right corner of the page ) --> just need to check about it
2- on the version 8.0.2 : it doesn't work as it s expected

**Comment by kpodemski** [comment]
Hummingbird should be tested only on PrestaShop 8.1+.

**Pull request closed without merging**
