### PR TITLE
Improved scss files structure

### LINKED ISSUE #270: Improved theme scss structure
We could improve with scss strucure.
Example with current `custom.scss`

```scss
// Components
@import "components/slider";
@import "components/currency-selector";
@import "components/language-selector";
@import "components/section-title";
@import "components/breadcrumb";
@import "components/category-tree/category-tree";
@import "components/search-filters/search-filters";
@import "components/category/header";
@import "components/category/subcategories";
@import "components/category/product-list";
@import "components/category/pagination";
@import "components/customer/customer-menu";
@import "components/customer/customer-link";
@import "components/cart";
@import "components/order-confirmation";
@import "components/brand";
@import "components/store";
@import "components/sitemap";
@import "components/address";
@import "components/table-wrapper";
@import "components/product/product-miniature";

// Modules
@import "modules/featuredproducts";
@import "modules/contactform";
@import "modules/contactinfo";
@import "modules/emailsubscriptions";
@import "modules/blockreassurance";
@import "modules/social-sharing";
@import "modules/imageslider";
@import "modules/mainmenu";

// Layout
@import "layout/header";
@import "layout/footer";
@import "layout/content";

// Pages
@import "pages/global";
@import "pages/login";
@import "pages/register";
@import "pages/checkout";
@import "pages/addresses";
@import "pages/orders";
@import "pages/product/product";
@import "pages/product/details";
```

It will be easier to read it this file would look like this:

```scss
// Components
@import "components";

// Modules
@import "modules";

// Layout
@import "layout";

// Pages
@import "pages";
```

Inside every directory we could place index.scss with aggregated all of that import.
Example with layout/index.scss:

```scss
@import "header";
@import "lfooter";
@import "content";
````

Inside custom.css only: 
```scss
@import "layout";
```

I will be also easier to remove move something form one directory to another. We just look at index.scss inside file that we are interest in. We don't have to search for it anywhere.

### PR DESCRIPTION
**Pull request by Oksydan**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Improved files structure and separated files by function. We current have two new directories inside scss directory. Vendors for bootstrap not abstract files and abstract for theme, vendors abstract scss code (variables, mixins, functions, placeholders etc). I know that is huge change we can discu cons and pros in comments section. 
| Type?             |  improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #270 
| How to test?      | Everything should work as before
| Possible impacts? | Different styling (should not occur)

### CODE REVIEW

**Review by NeOMakinG — APPROVED** [review]
Agree, it should be clearer to understand/read and modify 👍

**Comment by NeOMakinG** [comment]
@Hlavtox wdyt? Waiting for your stamp to merge!

**Review by Hlavtox — APPROVED** [review]
All good for me!

**Comment by NeOMakinG** [comment]
Thanks @Oksydan 👍

**Comment by mparvazi** [comment]
@NeOMakinG 

These two files have the same content:
```
src/scss/abstract/variables/bootstrap/_variable-overrides.scss
src/scss/abstract/variables/overrides/_overrides.scss
```

**Comment by Oksydan** [comment]
@NeOMakinG  ups sorry. 
File `src/scss/abstract/variables/bootstrap/_variable-overrides.scss` is never imported, so you can just remove it.

**Comment by NeOMakinG** [comment]
Yeah I will

**Pull request merged**
