### PR TITLE
Psgdpr module checkbox fix

### PR DESCRIPTION
**Pull request by JBLach**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | I have fixed psgdpr module checkbox
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes NA.
| How to test?      | See screenshots below
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

## Before
image

## After
image
image

### CODE REVIEW

**Comment by NeOMakinG** [comment]
Thanks @JBLach you're on fire these days 🔥 

I have a question, do you see any way to avoid that override?

**Comment by JBLach** [comment]
> I have a question, do you see any way to avoid that override?

Hi @NeOMakinG
Does this override cause any problems? Alternatively we can overwrite the front.js file and add these classes using js, but i don't think it's better solution, maybe someone else has an idea?

**Comment by JBLach** [comment]
> > > I have a question, do you see any way to avoid that override?
> > 
> > 
> > Hi @NeOMakinG Does this override cause any problems? Alternatively we can overwrite the front.js file and add these classes using js, but i don't think it's better solution, maybe someone else has an idea?
> 
> Adding an override means that if the module get updated, this override will probably not be updated in the future, it's always a bad idea in case we can avoid it, this is why I asked

Sure, i understand. I will think about a solution tomorrow

**Comment by JBLach** [comment]
Hi @NeOMakinG 

We can try to create a `block` in main module and extends the file, only changing the content in the block. WDYT?
```smarty
{extends file="modules/psgdpr/views/templates/hook/displayGDPRConsent.tpl"}
{block name='gdpr_checkbox'}
  <div id="gdpr_consent" class="mt-2 gdpr_module_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}">
    <span class="form-check">
      <input id="psgdpr_consent_checkbox_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}" name="psgdpr_consent_checkbox" type="checkbox" value="1" class="form-check-input psgdpr_consent_checkboxes_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}">
      <label class="form-check-label psgdpr_consent_message">
        {$psgdpr_consent_message nofilter}{* html data *}
      </label>
    </span>
  </div>
{/block}
```

**Comment by NeOMakinG** [comment]
> Hi @NeOMakinG
> 
> We can try to create a `block` in main module and extends the file, only changing the content in the block. WDYT?
> 
> ```
> {extends file="modules/psgdpr/views/templates/hook/displayGDPRConsent.tpl"}
> {block name='gdpr_checkbox'}
>   <div id="gdpr_consent" class="mt-2 gdpr_module_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}">
>     <span class="form-check">
>       <input id="psgdpr_consent_checkbox_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}" name="psgdpr_consent_checkbox" type="checkbox" value="1" class="form-check-input psgdpr_consent_checkboxes_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}">
>       <label class="form-check-label psgdpr_consent_message">
>         {$psgdpr_consent_message nofilter}{* html data *}
>       </label>
>     </span>
>   </div>
> {/block}
> ```

Does it work if the template comes from the module directly?

I guess it would be cleaner than overriding the whole file yes! I would agree.

@Hlavtox wdyt?

**Comment by JBLach** [comment]
> > Hi @NeOMakinG
> > We can try to create a `block` in main module and extends the file, only changing the content in the block. WDYT?
> > ```
> > {extends file="modules/psgdpr/views/templates/hook/displayGDPRConsent.tpl"}
> > {block name='gdpr_checkbox'}
> >   <div id="gdpr_consent" class="mt-2 gdpr_module_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}">
> >     <span class="form-check">
> >       <input id="psgdpr_consent_checkbox_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}" name="psgdpr_consent_checkbox" type="checkbox" value="1" class="form-check-input psgdpr_consent_checkboxes_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}">
> >       <label class="form-check-label psgdpr_consent_message">
> >         {$psgdpr_consent_message nofilter}{* html data *}
> >       </label>
> >     </span>
> >   </div>
> > {/block}
> > ```
> 
> Does it work if the template comes from the module directly?
> 
> I guess it would be cleaner than overriding the whole file yes! I would agree.
> 
> @Hlavtox wdyt?

I tested this solution and it works

**Comment by NeOMakinG** [comment]
> > > Hi @NeOMakinG
> > > We can try to create a `block` in main module and extends the file, only changing the content in the block. WDYT?
> > > ```
> > > {extends file="modules/psgdpr/views/templates/hook/displayGDPRConsent.tpl"}
> > > {block name='gdpr_checkbox'}
> > >   <div id="gdpr_consent" class="mt-2 gdpr_module_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}">
> > >     <span class="form-check">
> > >       <input id="psgdpr_consent_checkbox_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}" name="psgdpr_consent_checkbox" type="checkbox" value="1" class="form-check-input psgdpr_consent_checkboxes_{$psgdpr_id_module|escape:'htmlall':'UTF-8'}">
> > >       <label class="form-check-label psgdpr_consent_message">
> > >         {$psgdpr_consent_message nofilter}{* html data *}
> > >       </label>
> > >     </span>
> > >   </div>
> > > {/block}
> > > ```
> > 
> > 
> > Does it work if the template comes from the module directly?
> > I guess it would be cleaner than overriding the whole file yes! I would agree.
> > @Hlavtox wdyt?
> 
> I tested this solution and it works

Go for it! Seems way cleaner :)

**Review by NeOMakinG — APPROVED** [review]
So quick 🍬

**Comment by NeOMakinG** [comment]
I guess we need towait for psgdpr to be released before merging this

**Review by NeOMakinG — CHANGES_REQUESTED** [review]
Waiting for psgdpr release

**Review by kpodemski — APPROVED** [review]
gdpr module has been released, we can merge this :)

**Pull request merged**
