### PR TITLE
fix: The price is displayed twice as if there was a discount

### PR DESCRIPTION
**Pull request by tblivet**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Correct the issue 535
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixe https://github.com/PrestaShop/hummingbird/issues/535
| Sponsor company   | @PrestaShopCorp
| How to test?      | You can refer to the issue

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by mflasquin — APPROVED** [review]

**Review by aniszr — APPROVED** [review]
Hello @tblivet 

I tested your PR, the mentioned problem related to double display of prices in FO is solved, LGTM  :heavy_check_mark: 

See attached screenshot:
Cart

QA :heavy_check_mark:

**Review by Hlavtox — CHANGES_REQUESTED** [review]
@aniszr Hi, does it keep the crossed out price? I don't see it on the screenshot. If testing an issue that concerns discounts, you must test a product with a discount. :-)

It should be there, see figma prototype - https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?type=design&node-id=383-12713&mode=design

**Review by aniszr — APPROVED** [review]
Indeed I checked with a product with discount, see the attached screenshot below:

image

Thanks

**Review by boherm — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
Thanks @aniszr :-) Merging

**Pull request merged**
