### PR TITLE
Improved a11y for search form

### PR DESCRIPTION
**Pull request by nicosomb**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Improved a11y for search form
| Type?             | bug fix 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? | 

Related to https://github.com/PrestaShop/hummingbird/issues/251

### CODE REVIEW

**Review by 0x346e3730 — APPROVED** [review]

**Comment by kpodemski** [comment]
I think we'll need to have `$hookName` available to avoid having two elements with the same id.

**Comment by Hlavtox** [comment]
We can't have that ID there if we want to use multiple search forms, we must find another solution 👍

**Review by mflasquin — COMMENTED** [review]
If I am not mistaken, update a html element id is considered as a breaking change

**Comment by Hlavtox** [comment]
@mflasquin This is not core bro, we can do whatever we want here

**Comment by NeOMakinG** [comment]
> We can't have that ID there if we want to use multiple search forms, we must find another solution 👍

The theme is currently containing only one, it might not be a blocker for this PR but should be an improvement for the future

**Review by NeOMakinG — APPROVED** [review]
Give it a 🍬 because I feel like the ID not a theme blocker but more a core/ps_searchbar related problem or ever add `{$hookName}` to the ID to make it more unique

**Review by Hlavtox — APPROVED** [review]
Good for me, we can merge

**Review by kpodemski — CHANGES_REQUESTED** [review]
@nicosomb did you test it? is `$hookName` available and it has a correct value? You have to add a `hookName` to the view.

**Comment by nicosomb** [comment]
Hmm, in this module, it doesn't work.

**Comment by kpodemski** [comment]
@Hlavtox I would keep it simple and add a hookName variable to the search module

**Pull request closed without merging**
