### PR TITLE
Fix email subscription form UX on XS screen

### PR DESCRIPTION
**Pull request by mparvazi**
Part of #340 (Newsletter block)

## Before
Screenshot from 2022-07-08 20-51-41

## After (With last commit)
Screenshot from 2022-07-25 11-27-11

### CODE REVIEW

**Comment by Hlavtox** [comment]
I think we can put them like this by default (only padding-bottom) and put them on a line with bigger screen with media query. Less code. ;-)

**Comment by Hlavtox** [comment]
Also, WDYT?
178031718-0eac72e5-853b-4127-9c5d-10751bb5af38

**Comment by mparvazi** [comment]
Like this?

Screenshot from 2022-07-09 12-43-07

**Comment by SharakPL** [comment]
How about full width button when it's under the input? Otherwise [this version](https://github.com/PrestaShop/hummingbird/pull/344#issuecomment-1179501684) is good. Could be also `>` instead of `Subscribe` for mobile.

**Comment by mparvazi** [comment]
Screenshot from 2022-07-25 11-27-11

**Review by NeOMakinG — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Pull request merged**
